project:
  type: book
  output-dir: _book

book:
  title: "Panduan Pengguna SMART"
  author: "Muhammad Yoga Prabowo"
  
  favicon: images/favicon.png
  navbar:
    logo: images/PKNlogo.png
    title: "Sistem Manajemen Training Terpadu"

  chapters:
    - index.qmd
    - persiapan.qmd
    - penyelenggaraan.qmd
    - pasca.qmd
    - master.qmd
    - admin.qmd

format:
  html:
    theme: 
      - zephyr
      - custom.scss
    toc: true
    toc-title: "Di Halaman Ini"
    number-sections: true
    smooth-scroll: true
    search: true